<div id="h-browser">
<?php
$pompeii_id = "23";

$result = [
  "id" => $item->id(),
  "children" => [],
  "siblings" => [],
  "parents" => [],
];

$subjectValues = $item->subjectValues();
if($subjectValues){
  foreach ($subjectValues["p-lod:spatially-within"] as $value){
    $result['children'][] = $value->resource()->id();
  }
}

$p = $item->value("p-lod:spatially-within")->valueResource();

if ($p){

  $subjectValues = $p->subjectValues();
  foreach ($subjectValues["p-lod:spatially-within"] as $value){
    if($value->resource()->id() != $item->id()){
      $result['siblings'][] = $value->resource()->id();
    }
  }

  $i = 0;

  while($p->id() != $pompeii_id){
    $parentList = [];
    $parentList["id"] = $p->id();
    if($p->value("p-lod:geojson")){
      $parentList["geoJSON"] = $p->value("p-lod:geojson")->asHtml();
    } else {
      $parentList["geoJSON"] = "";
    }
    $parentList["siblings"] = [];
    $result["parents"]["p" . strval($i)] = $parentList;

    if($i > 0){
      $subjectValues = $p->subjectValues();
      foreach ($subjectValues["p-lod:spatially-within"] as $value){
        if($value->resource()->id() != $result["parents"]["p" . strval($i-1)]["id"]){
          $result["parents"]["p" . strval($i-1)]['siblings'][] = $value->resource()->id();
        }
      }
    }

    $i++;
    $p = $p->value("p-lod:spatially-within")->valueResource();
  }

  $result["parents"]["p" . strval($i)] = ["id" => $p->id(), "geoJSON" => $p->value("p-lod:geojson")->asHtml()];
  if($i > 0){
    $subjectValues = $p->subjectValues();
    foreach ($subjectValues["p-lod:spatially-within"] as $value){
      if($value->resource()->id() != $result["parents"]["p" . strval($i-1)]["id"]){
        $result["parents"]["p" . strval($i-1)]['siblings'][] = $value->resource()->id();
      }
    }
  }
}
krsort($result["parents"]);
?>

<h3>Spatial Hierarchy</h3>
<div>
<ul class="collapsibleList">
<?php foreach ($result['parents'] as $parent):?>
  <?php if( array_key_exists('siblings', $parent)): ?>
  <?php foreach ($parent['siblings'] as $sibling): ?>
      <li> <?php echo($this->api()->read('items', $sibling)->getContent()->linkPretty()); ?>
  <?php endforeach; ?>
  <?php endif; ?>
  <li> <?php echo($this->api()->read('items', $parent['id'])->getContent()->linkPretty()); ?>
  <ul>
<?php endforeach; ?>
  <?php foreach ($result['siblings'] as $sibling): ?>
      <li> <?php echo($this->api()->read('items', $sibling)->getContent()->linkPretty()); ?></li>
  <?php endforeach; ?>
<li> <?php echo($this->api()->read('items', $result['id'])->getContent()->linkPretty()); ?>
  <ul>
    <?php foreach ($result['children'] as $child): ?>
      <li> <?php echo($this->api()->read('items', $child)->getContent()->linkPretty()); ?>
  <?php endforeach; ?>
</li></ul>

<?php foreach (range(0, count($result['parents'])) as $number):?>
</ul></li>
<?php endforeach; ?>
</ul>
</div>

<div id="minimap">
<!-- div with geojson, populated by php call to api -->
<div id="minimap-geojson" style="display:none"><?php
echo $item->value('p-lod:geojson', ['type' => 'literal']);
?></div>


<div id="minimapid" style="width: 100px; height: 100px;display:none"></div>
<script>
// check if the item-geojson div has content and make a map if it does. 
if ($('#minimap-geojson').html().trim()) {
       $('#minimapid').show()

  var mymap = L.map('minimapid').setView([40.75, 14.485], 16);

  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    maxZoom: 19,
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
    id: 'mapbox.streets'
  }).addTo(mymap);

       L.geoJSON(JSON.parse($('#minimap-geojson').html())).addTo(mymap)
       
}
</script>
</div>
</div>